Gemfile, README.md, lib/dpl/provider.rb, lib/dpl/provider/packagecloud.rb, spec/provider/packagecloud_spec.rb
This PR introduces a provider for [packagecloud.io](https://packagecloud.io)
This provider allows users to push their `deb`, `dsc`, `rpm`, or `gem` build objects to their [packagecloud.io](https://packagecloud.io) package repository.
-  username:  the [packagecloud.io](https://packagecloud.io) user name
-  token: the [packagecloud.io](https://packagecloud.io) API token for the username specified
-  repository: the name of the [packagecloud.io](https://packagecloud.io) repository
-  local-dir: the directory where the package objects to push can be found
-  dist: the distribution string to use. The complete list of supported strings can be found on the [packagecloud.io docs](https://packagecloud.io/docs#os_distro_version)
```
dpl --provider=packagecloud
--username="${PACKAGECLOUD_USERNAME}" …
```
=> Add packagecloud.io provider

Gemfile, README.md, lib/dpl/provider.rb, lib/dpl/provider/chef_supermarket.rb, spec/provider/chef_supermarket_spec.rb
Upload Chef cookbooks to https://supermarket.getchef.com/
* **user_id**: Required. The user name at Chef Supermarket.
* **client_key**: Required. The client API key file name.
* **cookbook_category**: Required. The cookbook category in Supermarket (see: https://docs.getchef.com/knife_cookbook_site.html#id12 )
dpl --provider=chef-supermarket --user-id=chef --client-key=.travis/client.pem --cookbook-category=Others
=> Add Chef Supermarket provider

lib/dpl/provider.rb, spec/provider_spec.rb
In particular, we should skip 'gem install nokogiri' if
it's already available.
=> Skip installing a gem if it's already installed

lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
Hi there,
Using the pypi deployer. The first commands `setup.py register` and `setup.py sdist upload` work but the third one `setup.py upload_docs` fails with an authentication error. See the last lines of [this Travis job](https://travis-ci.org/jacquev6/LowVoltage/jobs/59508356) and [my .travis.yml file](https://github.com/jacquev6/LowVoltage/blob/master/.travis.yml).
This PR adds the `-r` option to the `upload_docs` command.
Thanks!
=> PyPI: upload_docs to the right server

lib/dpl/provider/elastic_beanstalk.rb, spec/provider/elastic_beanstalk_spec.rb
PR #230 relied on the `#option` method in order to access the value of the `bucket_path` option. Because of this if :bucket_path was left empty or nil the elastic beanstalk provider would error with `Missing bucket_path`. 
Instead add an accessor method for `bucket_path` which allows for :bucket_path to be nil this way if `bucket_path` is not specified deploys still work.
=> Make bucket_path option truly optional for elastic beanstalk provider

README.md, lib/dpl/provider/code_deploy.rb, lib/dpl/provider/elastic_beanstalk.rb, lib/dpl/provider/ops_works.rb, lib/dpl/provider/s3.rb
Try the env variables for AWS authentication if these options aren't set in the configuration.
For CodeDeploy, S3, OpsWorks and ElasticBeanstalk.
These environment variables are also [used by the aws cli app](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence).
This allows you to define the credentials once in the configuration, while deploying to multiple AWS services and/or using the AWS CLI.
=> Use environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

lib/dpl/provider/pypi.rb
ez_setup downloads "setuptools-$VER.zip", *not* "setuptools-$VER.tar.gz", so the file didn't get properly deleted.  This can lead to issues if we're deploying to multiple places (for example, if we deploy to PyPI, and then make a tarball and deploy elsewhere).
=> PyPI Provider: delete setuptools zip file

lib/dpl/provider/lambda.rb, lib/dpl/version.rb
This commit makes the lambda provider temporarily depend
on 2.0.37. This is because of the fact that when the
provider was implemented Lambda was in preview (version
2014-11-11). Now the Lambda API is at version 2015-03-31.
The new API is different than the old one, which breaks
the provider for this project.
This is a fix so that the existing provider works, but
the provider needs to be updated to conform to the newest
API.
=> Use specific version of aws-sdk for the Lambda provider.

README.md, lib/dpl/provider/elastic_beanstalk.rb
* Allow setting the environment name using environment variable `ELASTIC_BEANSTALK_ENV`. Use case: set the env name based on the current branch.
* Allow setting the version label for elastic beanstalk through environment variable `ELASTIC_BEANSTALK_LABEL`. Falls back to travis sha.
=> Environment variables for Elastic Beanstalk

README.md, lib/dpl/provider/ops_works.rb
Added custom_json options. If not set, will fallback to default configuration.
User have responsibility to set the custom_json value by himself. I assumed anyone who wanted to use custom_json already understand how to uses it.
closes #271
=> Opsworks Provider: added custom json options

lib/dpl/provider/npm.rb
For a more detailed example see: http://blog.getpiggybank.com/npm-private-modules-with-heroku/. I presume that this change is the only thing that's required, but I am unfamiliar with your infrastructure. (e.g. I don't know where NPM_API_KEY comes from.) 
I do know that npm publishing is currently failing using your instructions: http://docs.travis-ci.com/user/deployment/npm/. See, for example, this job: https://travis-ci.org/michaelleeallen/mocha-junit-reporter/jobs/67443955
=> Use the new .npmrc format

lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
This is a continuation of #253 and a reaction to the comment from the twine author and PyPI admin @dstufft: https://github.com/travis-ci/dpl/pull/288#discussion_r35265268
=> Don't auto register PyPI releases for less chance of MITM attacks.

Gemfile
'multipart-post' gem is required for 'testfairy' deployment
=> Added gem 'multipart-post'  for testfairy group

README.md
This was incorrectly documented as ELASTIC_BEANSTALK_VERSION
Can see the correct variable used in code [here](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/elastic_beanstalk.rb#L56)
=> Fix incorrect documentation of ELASTIC_BEANSTALK_LABEL

lib/dpl/provider/cloud_foundry.rb, spec/provider/cloudfoundry_spec.rb
We need to pass --skip-ssl-validation when we set the API endpoint, not to the login command
=> Fix: SSL validation issue when deploying to Cloud Foundry

lib/dpl/provider/packagecloud.rb, spec/provider/packagecloud_spec.rb
In some cases, eligible package or package-like objects may be laying
around (particularly .gem files in .bundle/ from a bundler driven test
suite). This allows the user to specify the glob(s) for the paths we
will search rather than a recursive search of everything.
This adds the option package_glob to the provider. It takes a string
or list of strings. It defaults to "**/*" (search everthing for package
files).
=> [packagecloud] Allow users to specify a package_glob we will search.

Gemfile, README.md, lib/dpl/provider/gae.rb, spec/provider/gae_spec.rb
This now uses Google's Cloud SDK towards a resolution for #94 
I see that tests are missing, but I'd rather like some opinion on the options and install routine beforehand.
And please bear with me, these are the first lines of Ruby in my life.
CC @BanzaiMan @waprin @ajessup @Trii
=> gae: Reimplement provider for Google App Engine

README.md, lib/dpl/provider.rb, lib/dpl/provider/azure_webapps.rb
:wave: from your friendly Microsoft Open Source team! We (and a bunch of our customers) use Travis all the time - and while we have deployments straight from GitHub, deploying only once Travis gave :+1: would be way better. This PR adds a provider for Azure Web Apps.
- Uses Git to deploy the actual files and to print the output of Azure's deployment engine
- Mandatory parameters: `--username`, `--password`, `--site`
- Optional parameter: `--quiet` (don’t print Azure’s deployment output)
Usage
```
dpl --provider=AzureWebApps --username=dpluser --password=deplp@ss --site=dplsite
```
Typical Azure Deployment Output
```
Installing deploy dependencies
Preparing deploy
No local changes to save
Deploying application
Deploying to Azure Web App 'travisdpltest'
remote: Updating branch 'master'. …
```
=> Add Provider for Azure Web Apps

Gemfile, README.md, lib/dpl/provider/s3.rb, spec/provider/s3_spec.rb
The V2 SDK does not require nokogiri, which takes longer to compile then the actual upload in some cases.
=> Use AWS SDK V2 for S3

lib/dpl/provider/boxfuse.rb, spec/provider/boxfuse_spec.rb
This fixes a bug in the previous PR.
=> Boxfuse provider: Fixed image/version paramater swap

lib/dpl/provider/cloud_foundry.rb, spec/provider/cloudfoundry_spec.rb
Change the way we download, install en run the CF CLI so we can run this on the container-based infrastructure
=> Feature: Update Cloud Foundry provider for container-based infrastructure

README.md, lib/dpl/provider/azure_webapps.rb
If users provide incorrect credentials, `git push` will print the given password cleartext. This PR changes from an optional 'quiet' mode to an opt-in verbose mode, triggered by passing the 'verbose' option.
=> Azure Provider: Change from opt-out 'quiet' to opt-in 'verbose'

lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
Deis provider installs `./deis` client and use it for add/remove SSH keys. In `deploy` task, provider [cleanup](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider.rb#L140) the working directory and so remove the deis client.
Later [`remove_key`](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider.rb#L154) silently fails due to missing executable.
This PR overwrite default `cleanup` for backup deis client before `git stash --all` executed by default [cleanup](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider.rb#L170).
I didn't write tests because I have no idea how to test that.
=> Deis: prevents Deis client to be cleaned

lib/dpl/provider/npm.rb, spec/provider/npm_spec.rb
@BanzaiMan sorry I dropped off the radar on helping with npm2 support (this is related to #309).
The npm provider still seems broken when using npm 2.  `publishConfig.registry` (and npm in general) expects you to include a protocol on your registry address, but that protocol should be stripped in the `.npmrc`.  This PR addresses that.
=> npm provider strips custom registry protocol

README.md, lib/dpl/provider/azure_webapps.rb
Azure uses different git url format for slot deployment (implemented in this PR):
```
https://{SLOT}.scm.azurewebsites.net:443/{SITE}.git
```
If **slot** config is not passed then the git url stays the same as it was previously:
```
https://{SITE}.scm.azurewebsites.net:443/{SITE}.git
```
This is not a breaking-change!
More about staging development in azure [read here](https://azure.microsoft.com/en-us/documentation/articles/web-sites-staged-publishing/).
Sorry but I don't have any build links to show since I'm using this provider only in private project...
=> Implement slot support for azure web apps deployment

lib/dpl/provider/modulus.rb, spec/provider/modulus_spec.rb
The command was not setting the ENV variable for MODULUS_TOKEN and was
failing with an exit status of 127.
=> Fixes #207 Modulus deploys failing without error

lib/dpl/provider/gcs.rb, lib/dpl/provider/s3.rb
Upgrading to mri 2.x would be preferrable, but in the meantime, this should help stop the bleeding on https://github.com/travis-ci/travis-ci/issues/5145
=> Pin mime-types to 2.x for mri 1.9

lib/dpl/provider/gae.rb
The "app" component was removed, and all "app" subcommands are now installed by default, as clarified in https://groups.google.com/forum/#!topic/google-cloud-sdk/NGIit4pTFQE
=> gae: Adapt to gcloud-0.9.88

README.md
=> Invalid option in Scalingo example

lib/dpl/provider/azure_webapps.rb
* Fixes travis-ci/travis-ci#5468
* In other words, makes it possible to deploy also from other branches than `master` to Azure Web Apps
Not-working build, without the fix:
https://travis-ci.org/kaplas/travis-azure-deployment-bug/builds/102781406#L160
Working build, when using this code change:
https://travis-ci.org/kaplas/travis-azure-deployment-bug/builds/102784628#L191-L207
Also the deployment history of the Web App itself confirms, that build number 1 never got through:
=> Fix Azure Web App Deployment from non-master branches

README.md, lib/dpl/provider/releases.rb, spec/provider/releases_spec.rb
Resolves https://github.com/travis-ci/travis-ci/issues/5424
Webhook is fired once when a GitHub Release is published. We defer publishing to the end, so that the first webhook notification for the ReleaseEvent contains the list of files in the payload.
Notice that if the deployment happens multiple times in a build matrix, the first will win.
=> Initially create a draft GitHub Releases 

lib/dpl/provider/bintray.rb
Given
```
{
"files":
[{"includePattern": "(.*\\.deb)", "uploadPattern": "$1",
"matrixParams": {
"deb_distribution": "stable",
"deb_component": "main",
"deb_architecture": "amd64"}
}
]
}
```
We would end up with "" as `root_path`, and we get
```
[Bintray Upload] Warning: Path:  does not exist.
```
This commit fixes this issue.
=> [bintray] Construct file path properly when includePattern starts with '('

README.md, lib/dpl/provider/elastic_beanstalk.rb, spec/provider/elastic_beanstalk_spec.rb
Hey Gents,
These commit add an only_create_app_version option to the elastic beanstalk provider. This makes it so the version is uploaded without making it active.
Thanks.
=> ElasticBeanstalk option for only_create_app_version

README.md, lib/dpl/provider/releases.rb, spec/provider/releases_spec.rb
Sometimes we want to updating an existing release with a new file that
has the same name. While best practice for user-facing releases is to
make a brand new release, there are some use cases where releases are
used as well known endpoints to grab the latest code.
This commit adds support for an `overwrite` option for the releases
provider, which will upload files even if others with the same name
are present on the release.
=> Allow Github release provider to overwrite files

README.md
Hello, I am with JFrog (home of Bintray). There was a small change that was needed to be made for the documentation of the Bintray provider section:
"Removed small documentation mistake about having to use brackets for the excludePattern param in the bintray descriptor example."
We have verified this to be incorrect. There is no need to use brackets for the 'excludePattern' param.
Thank you.
=> Update README.md for the bintray provider

lib/dpl/provider/gae.rb, spec/provider/gae_spec.rb
When deploying it'll allow to let the container builder to perform the docker builds as per google docs. https://cloud.google.com/sdk/gcloud/reference/config/set
use_cloud_build
If True, use the Container Builder API to perform docker builds, rather than a temporary VM. See https://cloud.google.com/container-builder/docs/ for more information.
=> Add cloud-build option to GAE 

README.md, lib/dpl/provider.rb, lib/dpl/provider/launchpad.rb, spec/provider/launchpad_spec.rb
This PR adds support to trigger a code import on [launchpad.net](http://launchpad.net). This is useful to, for example, build and host Ubuntu packages.
Example [config](https://github.com/HPI-BP2015H/test/blob/master/.travis.yml#L3-L14) and [build](https://travis-ci.org/HPI-BP2015H/test/builds/118020367).
/cc: @timfel
=> Launchpad support

README.md, lib/dpl/provider/lambda.rb
This should fix #397. Amazon Lambdas now support four different runtimes.
=> Allow for runtime to be an option for lambdas

Gemfile, lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
This is for #352. Although for some reason just using master seemed to work, it does seem that there is a timing issue that should be explicitly solved.
The problem seems to be that Deis reports ssh keys are added slightly before they can actually be used for a code push. In my testing it seems to take < 2 seconds for the key to be usable.
This code just gets the deis remote information from the git config file (for some reason `git remove -v show deis` was not working) and attempts to SSH into the remote until it gets a 'PTY allocation request failed message'. That doesn't seem like the cleanest way of going about it, but since you can't actually SSH in it was the only test I could come up with. Seems to work for me.
Edit: I realize that this doesn't pass tests right now, if this …
=> Add a check to wait for the SSH key to start working

lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
In the past the output from the deis push has been garbled due to git prepending a 'remote:' prefix combined with the deis-builder adding a e[1G unprintable character to attempt to clean it up. Travis did not handle that character as expected and would display the output wrong. These changes attempt to clean up the output so that it can be correctly displayed in travis.
Below is a sample of the output before and after this change.
```
remote:  buildpack
remote: remote: /heroku/heroku-buildpack-ruby.git
remote: ework: Ruby
remote: piling Ruby/Rack
remote: remote: remote: ent:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote: remote: remote: remote: initest 5.8.3
remote: remote: remote: espath 1.1.3
remote: remote: ime-types 2.99
remote: ini_portile2 2.0.0 …
```
=> Clean up output from the git push to deis and fix tests.

lib/dpl/provider/elastic_beanstalk.rb, spec/provider/elastic_beanstalk_spec.rb
This PR adds a possibility to finish the build after ElasticBeanstalk environment update completes, if `wait_until_deployed` config option provided. It also prints out EB events messages during the build.
Tested both failing and successful builds:
Failing build (reason - broken .ebextensions config file): [23984152](https://travis-ci.com/planorama/PlanoLive/builds/23984152)
Successful build: [37741814](https://travis-ci.com/planorama/PlanoLive/jobs/37741814)
=> ElasticBeanstalk provider: finish the build after EB env update completes

README.md, lib/dpl/provider/gae.rb, spec/provider/gae_spec.rb
`use_cloud_build` and `docker_build` options had already been deprecated in Google Cloud SDK v112.0.0 and removed in Google Cloud SDK v114.0.0
If we kept the `use_cloud_build` option, we will get the error below while deploying to GAE with Google Cloud SDK v114.0.0:
`ERROR: (gcloud.config.set) Section "app" has no property "use_cloud_build".`
If we kept the `docker_build` option, we will get the error below while deploying to GAE with Google Cloud SDK v114.0.0:
```
ERROR: (gcloud.preview.app.deploy) Docker builds now use Container Builder by default. To run a Docker build on
your own host, you can run:
docker build -t gcr.io/<project>/<service.version> .
gcloud docker push gcr.io/<project>/<service.version>
gcloud preview app deploy --image-url=gcr.io/<project>/<service.version>
```
This …
=> Fix Google Cloud SDK v114.0.0 GAE deploy error

README.md, lib/dpl/provider.rb, lib/dpl/provider/s3.rb, spec/provider_spec.rb
We're running into issues where AWS isn't getting our charset right. This allows us to specify it for text files.
=> Allow users to specify default text charset

Gemfile, README.md, lib/dpl/provider/ops_works.rb, spec/provider/ops_works_spec.rb
Hey this PR updates the AWS OpsWorks provider.
- switch to aws sdk v2
- add layer-ids option to opsworks deployment
- fix access key id lookup
afterwards it should be possible to add the `layer-id` option to the .travis.yml like:
```yml
deploy:
provider: opsworks
app-id: <app-id>
layer-ids:
- <layer-id>
```
This PR relates to #191 travis-ci/travis-ci#2905
=> Update OpsWorks deployment

lib/dpl/provider/chef_supermarket.rb
To be ruby 1.9 compatible we already enforced chef <12
Chef 11.18 needs mime-type ~> 1.16
This PR do the same as #365 but for chef_supermarket provider
Cc: @aboten
=> Pin mime-type for chef_supermarket provider

lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
Hi,
We ran into some issue when using dpl with the deis provider. In some case the build triggered by deis failed but the error was not caught by dpl.
This fix remove the piped script on the `git push` and instead check the returned status code.
=> Deis provider: unthrow error on push_app

README.md
The ruby version in [dpl.gemspec](https://github.com/travis-ci/dpl/blob/63cf1de1e482d90ba12ad06d16a96c135b4c16b7/dpl.gemspec#L17) does not match what is in the [README](https://github.com/travis-ci/dpl/blob/63cf1de1e482d90ba12ad06d16a96c135b4c16b7/README.md#installation). This PR corrects the README.
=> Changed required ruby version in README from 1.8.7 to 1.9.3

README.md, lib/dpl/provider/s3.rb, spec/provider/s3_spec.rb
Add support for S3 Storage Classes.
AWS Docs here: https://aws.amazon.com/s3/storage-classes/
=> Fix #291, add support for S3 storage class

lib/dpl/provider/atlas.rb
- Better handling of an empty `$GOPATH`
- the way `dpl` sets `GIT_HTTP_USER_AGENT` seems
to cause issues with `go get` now, but removing it
resolves the issue
- No longer any need to `make` the binary, `go get ...`
installs and makes a working binary
=> Fixes issue with `go get atlas-upload-cli` not working

README.md
Default Heroku deploy strategy is `api` and `anvil` doesn't work.
=> Fix Heroku instructions in README

README.md
Add the missing options `access_key_id`, `secret_access_key`, and especially `region` for AWS Lambda function in the README
=> Add doc for missing AWS Lambda options

lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
#479 wasn't working as expected. PIPESTATUS is a bash feature and the context.shell is a simple sh session. The result of this would be that all deploys would get marked as failed. 
To fix this I am executing the deployment in a bash session.
=> Deis provider needs to execute push in bash

lib/dpl/provider/azure_webapps.rb, spec/provider/azure_webapps_spec.rb
The script below was unable to push the build to a freshly created Azure Web app, because 
an empty Azure website doesn’t have a Git `HEAD` yet so the deployment fails.@felixrieseberg
Here is a link to a successful build and deploy after my changes.
https://travis-ci.org/A92hm/travis-azure
=> Azure web apps: Enabling push to an empty repository

lib/dpl/provider/cloud_foundry.rb, spec/provider/cloudfoundry_spec.rb
The Cloud Foundry CLI now uses a single dash instead of double.
=> Fixes Cloud Foundry deployment

lib/dpl/provider/heroku/git.rb, spec/provider/heroku_git_spec.rb
Heroku rejects pushes from a shallow clone like ours since Heroku
may not have all the objects necessary to build the application
reliably.
=> Unshallow before Heroku git deployment

lib/dpl/provider/anynines.rb, spec/provider/anynines_spec.rb
This PR fixes the URL needed for Anynines and fixes the `cf login` command.
=> Fix anynines support

Gemfile, lib/dpl/provider/releases.rb
Since version 4.4.0 requires Ruby 2.x.
Resolves https://github.com/travis-ci/travis-ci/issues/6772
=> Pin octokit to `~> 4.3.0`

lib/dpl/provider/code_deploy.rb
aws-sdk 3.0.0.rc1 has incorrect dependency.
See https://github.com/aws/aws-sdk-ruby/issues/1356
=> Pin aws-sdk to '~> 2.6.32' for CodeDeploy

README.md, lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
*Fix https://github.com/travis-ci/dpl/issues/334, close https://github.com/travis-ci/dpl/pull/349*
This is a rebase and slight refactor of work from @eric-takealot in https://github.com/travis-ci/dpl/pull/349 after a merge conflict from https://github.com/travis-ci/dpl/pull/396.
> Has this been tested?
@BanzaiMan https://github.com/travis-ci/dpl/pull/349#issuecomment-149536356
With `skip_upload_docs: true`: https://travis-ci.org/lukeyeager/DIGITS/jobs/172784593
With `skip_upload_docs: false`: https://travis-ci.org/lukeyeager/DIGITS/jobs/172785158
=> [PyPI] Add option to skip uploading documentation

lib/dpl/provider/npm.rb
Trying to add support of npm publish tags.
I see people was already asking for this feature for some time: https://github.com/travis-ci/dpl/issues/415
Here is a build conf which is using added feature: https://travis-ci.org/mamont/test-travis-proj/
It's first time I see ruby, but I'm eager to address any possible comments in order to have that (or similar) functionality in mainstream.
=> Add npm publish tags support

lib/dpl/provider/packagecloud.rb, lib/dpl/version.rb
Bumps the [`packagecloud-ruby`](https://github.com/computology/packagecloud-ruby) client in the [`packagecloud`](https://github.com/travis-ci/dpl#packagecloud) provider to [`v1.0.5`](https://rubygems.org/gems/packagecloud-ruby/versions/1.0.5) which fixes several bugs and adds python support.
https://github.com/computology/python-test-packages/blob/master/.travis.yml#L20
https://travis-ci.org/computology/python-test-packages#L1348
https://travis-ci.org/capotej/http/builds/182718448
https://github.com/capotej/http/blob/master/.travis.yml#L34
Not sure if any authentication/verification is needed, but [I work for packagecloud.io](https://github.com/orgs/computology/people).
Let me know if you need anything else to merge this, thanks!
=> packagecloud client bump to 1.0.5

lib/dpl/provider/deis.rb, spec/provider/deis_spec.rb
I ran into an issue while trying to setup two deis deploys in my `.travis.yml` file. The same remote name ("deis") is currently used for both, which causes the second to error with the following message:
```
Error: Remote deis already exists, please run 'deis git:remote -f' to overwrite
```
This PR sets the remote name to the unique combo of controller-app. Some other implementation ideas include:
- allow the user to set a `remote` options -  this doesn't seem necessary if we can generate a unique name, nor do I see it being useful for any other situation
- specify the `-f` option to the `git:remote` command
I ended up going with creating a separate remote for each deploy instead of using `-f` because it mimics the way we perform manual deploys. If anyone has strong opinions on other …
=> Set remote to unique value in Deis provider

README.md, lib/dpl/provider/s3.rb, spec/provider/s3_spec.rb
A small change to add support for encryption artifacts uploaded to AWS S3. Default to false to avoid 
breaking existing users. Docs are updated, but my rspec is very rusty. Would appreciate assistance/
mentoring to get a proper test created.
=> Add support for Server-Side Encryption to S3 Provider

lib/dpl/provider/gae.rb, spec/provider/gae_spec.rb
In gcloud sdk v138.0.0,
gcloud app deploy with args `--version ""` will get error below:
ERROR: (gcloud.app.deploy) argument --version/-v: Bad value []: May only
contain lowercase letters, digits, and hyphens. Must begin and end with
a letter or digit. Must not exceed 63 characters.
So, if user didn't set the version and we want to use the gcloud
default generated version in this deployment, we just don't add
`--version`.
=> Fix GAE deployment version error in gcloud sdk v138.0.0.

lib/dpl/provider/packagecloud.rb
This fixes a [regression](https://github.com/computology/packagecloud-ruby/issues/19) introduced with the [my latest changes to dpl](https://github.com/travis-ci/dpl/pull/541)
Tested this branch with every package type we support:
[travis job](https://travis-ci.org/computology/python-test-packages#L1352)
[travis.yml](https://github.com/computology/python-test-packages/blob/master/.travis.yml#L20)
[travis job](https://travis-ci.org/computology/rubygem-test-package#L466)
[travis.yml](https://github.com/computology/rubygem-test-package/blob/master/.travis.yml#L17)
[travis job](https://travis-ci.org/capotej/http/jobs/184411156#L953)
[travis.yml](https://github.com/capotej/http/blob/master/.travis.yml#L34)
[travis job](https://travis-ci.org/capotej/http/jobs/184411161#L950) …
=> Fix Rubygems support for packagecloud provider

Gemfile
`nokogiri` used by gem `aws-sdk-v1` (for elastic beanstlak deployments) was updated on December 27 to version 1.7.0 from 1.6.8.1
The newer version uses ruby >=2.1.0
As a temporary change, to avoid making big changes during feature freeze, I am pinning nokogiri to ~>1.6.8
=> Pin nokogiri at ~>1.6.8 that uses ruby >=1.9.2

Gemfile
`nokogiri` used by gem `aws-sdk-v1` (for elastic beanstlak deployments) was updated on December 27 to version 1.7.0 from 1.6.8.1
The newer version uses ruby >=2.1.0
As a temporary change, to avoid making big changes during feature freeze, I am pinning nokogiri to ~>1.6.8 that works with ruby >=1.9.3
=> Pin nokogiri at 1.6.8 that works with ruby 1.9.3

lib/dpl/provider/elastic_beanstalk.rb
... instead of the [earlier solution](https://github.com/travis-ci/dpl/pull/555) of fixing it in the Gemfile, since the provider class installs the `aws-sdk-v1` gem during runtime
=> Pin nokogiri version in provider class

lib/dpl/provider/gae.rb, spec/provider/gae_spec.rb
Amending pull #563 to include printing the python2.7 version before installing and executing gcloud and escaping the apostrophes.
=> amend #563, test for apostrophe

lib/dpl/provider/gae.rb, lib/dpl/version.rb, spec/provider/gae_spec.rb
Resolves https://github.com/travis-ci/travis-ci/issues/6913.
This works by spawning a new bash process, activate Python 2.7, and execute the commands. See the issue above for tests.
=> Invoke GAE deployment commands with Python 2.7

README.md
Three headings in the readme were not rendered correctly. I guess this is because of the [recent markdown changes](https://githubengineering.com/a-formal-spec-for-github-markdown/)?
=> Fix broken markdown headings in README

lib/dpl/provider/code_deploy.rb
This **PR** enable `aws-sdk` `2.8` instead of `2.6`
Successful build on https://travis-ci.org/waghanza/dpl/builds/210637656
=> Use the last SDK version

lib/dpl/provider/rubygems.rb, spec/provider/rubygems_spec.rb
I believe this one line of logging will help clarify errors people get when their git repo name doesn't match up with the gem name they are attempting to deploy. See: https://github.com/travis-ci/dpl/issues/574
Here is a build with the additional log line added: 
https://travis-ci.org/sepulworld/tfmod-generator/builds/234107707#L232
If RubyGems responds with:
```
/home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/json/common.rb:155:in `parse': 776: unexpected token at 'This rubygem could not be found.' (JSON::ParserError)
```
We will easily see the discrepancy with the gem name we are trying to lookup and that gem name we expect it to be looking up.
=> add additional logging to clarify what gem dpl is looking up

lib/dpl/provider/heroku/generic.rb, spec/provider/heroku_api_spec.rb, spec/provider/heroku_git_spec.rb
Heroku retired the older VPI versions https://devcenter.heroku.com/changelog-items/1147, and we need to adopt to V3 on all Heroku API calls, including `#get_user`.
Tested: https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/235764486#L770
=> Adopt to Heroku API V3

lib/dpl/provider/heroku/api.rb, spec/provider/heroku_api_spec.rb
We missed these in the previous PR #642.
=> Add Heroku API v3 header to `curl` commands

lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
The old 'https://pypi.python.org/pypi' will be shut down on
2017-07-03.
https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html
See also https://github.com/travis-ci/dpl/issues/655
=> Switch the default PyPI server to https://upload.pypi.org/legacy/

README.md, lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
https://github.com/travis-ci/dpl/issues/660 points to the change in default behavior. We should recognize this change, and change the default.
I think this is less risky than usual, since the default now leads to deployment failure.
This resolves #665.
=> Skip upload_docs by default for PyPI provider

README.md, lib/dpl/provider/firebase.rb, spec/provider/firebase_spec.rb
Adds support for adding optional messages when deploying with the Firebase provider.
Please take a look at `spec/provider/firebase_spec.rb` as I'm not totally sure how the test should be.
Fixes travis-ci/travis-ci#7872
=> Add support for message in Firebase provider

Gemfile, lib/dpl/provider/code_deploy.rb, lib/dpl/provider/elastic_beanstalk.rb, lib/dpl/provider/lambda.rb, lib/dpl/provider/ops_works.rb, lib/dpl/provider/s3.rb
[`aws-sdk` 3.0](https://rubygems.org/gems/aws-sdk/versions/3.0.0) was released earlier today, and this results in problems if multiple different AWS deployments are configured (most notably CodeDeploy, which _requires_ S3).
The manifestation is such that `gem` waits for user input that never comes, to confirm whether or not `aws.rb` should be overwritten: https://travis-ci.org/BanzaiMan/travis_production_test/builds/269741234#L571-L573
This PR fixes this issue by specifying `< 3` in the `gem install -v` command. Here, we will assume that the previous `~> 2.*` strings are no longer necessary, since sufficient time has passed and it is not longer a concern to drop it. (`gem install -v` cannot take multiple such specifications)
=> Pin `aws-sdk` to < 3

lib/dpl/provider/code_deploy.rb, lib/dpl/provider/elastic_beanstalk.rb, lib/dpl/provider/lambda.rb, lib/dpl/provider/ops_works.rb, lib/dpl/provider/s3.rb
Previous '< 3.0' was too lax, resulting in some cases installation
of '1.x'
Resolves https://github.com/travis-ci/dpl/issues/685.
=> Pin aws-sdk to '~> 2.0'

lib/dpl/provider/openshift.rb
More recent versions require net-ssh 4.0.0, which is not compatible
with Ruby 1.9.x.
Resolves https://github.com/travis-ci/dpl/issues/595.
=> Pin net-ssh-gateway to ~> 1.3.0

lib/dpl/provider/pages.rb
Prevents build/deploy errors when more than 10k files are `git commit`'d and the build log grows too large.
=> Truncate output of git commit in pages provider

README.md, lib/dpl/provider/pages.rb
Closes travis-ci/travis-ci#7562
Resolves #704 
This duplicates efforts of #715, but a bit differently. I wrote it a long time ago, but was unsure whether it's ready. Now I think it's better to present this code to public at least.
The design of this feature is also based on my analysis of [some npm packages](https://www.npmjs.com/search?q=gh-pages) providing similar behavior.
@jyasskin please check it out.
-------------
https://travis-ci.org/webknjaz/dpl-gh-pages/builds/323649670
(It's got checks for non-existing branch on remote, for enabled and for disabled force push, for `committer-from-gh` option, and check for invalid token — that's why it's errored in the end and it's okay)
* **keep-history**: Optional, create incremental commit instead of doing push force, defaults to false.
* …
=> Enable gh-pages to retain deploy branch history

lib/dpl/provider/pages.rb
Make `local-dir` rely on `TRAVIS_BUILD_DIR` env variable if available.
Ref #9047.
=> Fix side-effect of broken/changed cwd in GitHub Pages deployment provider

README.md, lib/dpl/provider/pages.rb
Adds a simple option to be set on `.travis.yml` deploy section, just as the others, to be able to disable the creation of such file. It could be deleted with a complicated after_deploy but I don't see why a simple option cannot be provided.
=> Add option to disable "Deployed at [time]" file

lib/dpl/provider/ops_works.rb
This way, an actual JSON string can be given as `custom_json`
parameter.
Otherwise, when an actual JSON string is given via the parameter,
we turn *that* into a string.
=> Ensure `#custom_json` is JSON, not Ruby object

lib/dpl/provider/code_deploy.rb, spec/provider/code_deploy_spec.rb
It is possible to deploy CodeDeploy app without authorization to run `head_object`. When we encounter such an error, we should move on and fall back to the default behavior.
This resolves https://github.com/travis-ci/dpl/issues/741.
=> Fix CodeDeploy provider when key isn't authorized to run `head_object`

.travis.yml, README.md, Rakefile, dpl-rubygems.gemspec, gemspec_helper.rb, lib/dpl/provider.rb, lib/dpl/provider/bintray.rb, lib/dpl/provider/pages.rb, lib/dpl/provider/rubygems.rb, spec/provider/lambda_spec.rb, spec/provider/rubygems_spec.rb, spec/provider_spec.rb
This PR lays ground work for the planned 1.9.0 release.
1.9.0 will introduce some significant changes to `dpl` as a tool.
1. `dpl` now requires Ruby 2.2.
1. Each deployment provider code will now be a separate gem. This allows the dependencies of each provider to be managed separately.
1. Drops Appfog support. The dependent gem [`af`](https://rubygems.org/gems/af/versions/0.3.22) has not been maintained and depends (indirectly) on an older version of `json`, which cannot be built on Ruby 2.2. See https://travis-ci.org/travis-ci/dpl/jobs/343764202#L3110
1. Adds `gemspec_glob` option to RubyGems provider in order to allow multiple gems to be built and uploaded.
1. Test on Ruby 2.2, 2.3, 2.4, 2.5.
=> Version 1.9 ground work

README.md, lib/dpl/provider/pypi.rb, spec/provider/pypi_spec.rb
This allows deployment not to fail if a file is already present on the PyPI server.
This fixes travis-ci/travis-ci#7851
You can find 3 builds using this commit:
Option not set, deployment fails because of existing files on the server (same behavior as before): https://travis-ci.org/mayeut/gcovr/builds/339567990
Option set to false, deployment fails because of existing files on the server: https://travis-ci.org/mayeut/gcovr/builds/339578927
Option set to true, deployment succeeds, skipping existing files on the server: https://travis-ci.org/mayeut/gcovr/builds/339580501
=> PyPI: Add skip_existing option

lib/dpl/provider/npm.rb, spec/provider/npm_spec.rb
Hey,
this PR adds logging for the provided api-key to the npm provider. This will only display the last 4 characters and obfuscate the rest. It helped me personally getting the npm deploy running, as I mistakenly encrypted the values wrongly (I used --pro with the travis cli although this repo was public and --org would have been correct).
=> update npm deploy provider to see parts of the key

lib/dpl/provider/lambda.rb
Resolves #745, making the Lambda provider consistent with other dpl AWS offerings. This code is lifted from the [S3](https://github.com/travis-ci/dpl/blob/e6a53d8f4cb4ce76b1ce3a301af348b3f8ee8547/lib/dpl/provider/s3.rb#L21-L34) provider. I'll admit these are the first lines of Ruby I've ever written - do let me know if there are any improvements to be made!
As changes to Travis environment variables do not require making commits, this modification will allow me to rotate AWS credentials for all my repositories via the Travis API much more easily.
In accordance with the contributing guidelines, I tried using this branch for deployment of one of my own projects, and it [succeeded](https://travis-ci.org/gebn/commute-weather/builds/343432756).
=> Allow providing AWS credentials via environment variables in the AWS Lambda provider

lib/dpl/provider/releases.rb, spec/provider/releases_spec.rb
These are passed on to Octokit, so the values should be booleans,
not strings.
Resolves #613.
=> Handle "true"/"false" in GitHub Releases flag

lib/dpl/provider/ops_works.rb
Adding new option to also have the application source updated.
Problem: travis only creates deployment but this won't update the settings where one would see the current deployed version. Setting the flag `update-app-on-success` to `true` updates the settings after the deployment was successful.
```yml
deploy:
provider: opsworks
access_key_id: abcdefg
secret_access_key: ultrA-5ecr3t
app-id: 11223344-5566-7788-9900-aabbccddeeff
on:
branch: master
wait-until-deployed: true
update-app-on-success: true
```
An opsworks-user with the permission to deploy and to update-app is required.
See successful run here: https://travis-ci.com/easybib/bib-cd/builds/68564088
=> Opsworks: Update application source setting after successful deploy

lib/dpl/provider/s3.rb
Aws and multithreading may not play well at all times.
See https://aws.amazon.com/blogs/developer/threading-with-the-aws-sdk-for-ruby/
for more details.
Resolves #788.
=> Define Aws constants up front

README.md, dpl-hephy.gemspec, lib/dpl/provider.rb, lib/dpl/provider/hephy.rb, spec/provider/hephy_spec.rb
Hi dpl gem maintainers,
Recently the deis.io website was taken off the web by the Deis team and this has caused the dpl gem to be broken as the deis cli install script is being pulled from that website. I'm one of the maintainers of the Hephy fork (https://github.com/teamhephy) of Deis Workflow. We are the only public fork that we know of right now. I have written another Hephy provider that we will maintain on our side when we build our own CLI. For now the Deis provider is sufficient for us, but the Hephy provider we will be moving towards in the future.
Many users of Deis and Hephy also use the dpl gem in CI environments for deployments and we would please like to merge this in ASAP in order to fix the install script location.
Any question please ask.
anton
=> Fixing Deis and adding Hephy provider

lib/dpl/provider/firebase.rb, spec/provider/firebase_spec.rb
Currently, the build passes even though deployment failed:
https://travis-ci.org/SamirTalwar/friendlychat-web/builds/418938360
With this fix, the build fails when there is a deployment failure:
https://travis-ci.org/SamirTalwar/friendlychat-web/builds/418939206
=> Raise an error if Firebase deployment fails.

lib/dpl/provider/releases.rb, spec/provider/releases_spec.rb
The overwrite logic for GitHub Releases first checks to see if an asset with the given name already exists, and if so deletes it to make way for the new upload.  If, for some reason, a match is overlooked, the asset
is not deleted, and the upload errors with 422 Validation Failed, code "already_exists" and field "name".
The "some reason" in this case was that only the first page of assets are returned in-line with the releases() call.  Using release_assets() directly will trigger the paginate logic in Octokit and fix the problem.
Here is an example of a build [failing to find and delete](https://travis-ci.org/djpohly/PKGBUILD/builds/414689202#L561) an existing asset from a release, and a build using the PR branch which [successfully overwrites …
=> Fix GitHub deployment failure when overwriting assets

README.md, lib/dpl/provider/lambda.rb, spec/provider/lambda_spec.rb
Extended the file ext test in `zip_file()` to include .Jar file extensions with .zip file extensions to be copied to Lambda.
Added tests for the new condition
Fixes #838
=> Allowed .jar files to be copied to lambda function

lib/dpl/provider/s3.rb
Users may end up uploading thousands of files, which will eat up log 
capacity.
=> Provide `quiet` option to S3 provider

lib/dpl/provider/firebase.rb
In order to support multiple Hosting sites. See https://github.com/firebase/firebase-tools/releases/tag/v4.2.0
Successfully tested on a private repo.
=> Upgrade firebase-tools

README.md, dpl-cargo.gemspec, lib/dpl/provider.rb, lib/dpl/provider/cargo.rb, spec/provider/cargo_spec.rb
Example job: https://travis-ci.com/Nemo157/nemo157-rs/jobs/130213124
This is a trivial first integration. It would be possible to add more options like which registry to push to, but those can be left to a future PR.
=> crates.io provider for publishing Rust packages

lib/dpl/provider/heroku/api.rb, spec/provider/heroku_spec.rb
This endpoint has been deprecated for years, and we are looking into removing it.
As such, it is currently browned out and will be permanently removed in 2 weeks.
See https://devcenter.heroku.com/changelog-items/1486
This PR stops using that endpoint, to use the standard build one.
=> Stop using heroku build result endpoint

lib/dpl/provider/rubygems.rb, spec/provider/rubygems_spec.rb
The `gemspec` option is for specifying the `*.gemspec` file to build the gem(s), and it should not influence the gem file to push.
Resolves #908.
To test:
```yaml
deploy:
provider: rubygems
edge:
branch: rubygems-gem-detection
⋮ # rest
```
=> Ignore gemspec option when looking for gem file to upload

lib/dpl/provider.rb, lib/dpl/provider/atlas.rb, lib/dpl/provider/releases.rb, lib/dpl/provider/script.rb, spec/provider/releases_spec.rb
This PR adds to Releases:
1. Message when a file is not uploaded (Resolves #842)
1. Creates a draft release correctly when `draft: true` is passed. (Resolves #914)
=> Releases improvements

gemspec_helper.rb, lib/dpl/provider/heroku/api.rb, lib/dpl/provider/heroku/generic.rb, spec/provider/heroku_spec.rb
When deprecating the build result endpoint, we didn't see dpl was still using that endpoint due to the lack of custom User Agent, which led us to fix it a bit late (https://github.com/travis-ci/dpl/pull/917).
This sets a custom user agent, to prevent this kind of issue from happening again.
=> Set a custom user-agent for all heroku API calls

dpl-cloud_files.gemspec, spec/provider/snap_spec.rb
Fixes test asserting a specific error is thrown when pushing multiple
snaps. Previous version of test expected a specific error message, which
assumed `Dir.glob` returned results in a specific order, which is system
dependent. ~This fix uses `Dir.glob` in the test itself.~ This fix uses regex to match the error message more flexibly.
=> Fixes test for multiple snaps error

spec/provider/testfairy_spec.rb
These are making external HTTP calls to a currently unresponsive server.
=> Skip testfairy specs

dpl-gcs.gemspec, dpl-releases.gemspec, dpl-s3.gemspec
The Github Releases, AWS S3, and Google Cloud Storage providers use the mime-types gem 2.x. This PR changes them to use mime-types gem 3.x.
The mime-types gem 2.x was no longer supported as of 2017-11-21. 
This means that new mime-types added in mime-types 3.x are not being uploaded with the correct Content-Type.
This solves my particular problem of webassembly files not having the correct Content-Type on AWS S3, but hopefully it makes life a little easier for other users too at some point.
`rake spec-releases spec-gcs spec-s3` shows no failures, and I have a working deployment using my fork: https://travis-ci.com/jonstites/game_of_life/jobs/191123300
=> Upgrade mime-types gem

dpl-chef_supermarket.gemspec, dpl-pages.gemspec
3.1.0 requires Ruby 2.3, which is not suitable for our releases
just yet.
Fixes #995.
=> Resolve `public_suffix` and `ohai` dependency

lib/dpl/provider/pages.rb
Instead ignoring symbolic links while deploying to GitHub Pages, the PR proposes to include symbolic links on deploy, which particularly benefit builds that bypasses Jekyll via `.nojekyll`.
=> Copy GitHub Pages symbolic links

README.md
- "npm" should be lower-case
- npm terminology is "token" _(vs. api-key)_ for user familiarity
=> npm label updates

lib/dpl/provider/scalingo.rb, spec/provider/scalingo_spec.rb
* Added `--region` flag: Scalingo is now [available on multiple regions](https://scalingo.com/articles/2019/07/01/new-osc-fr1-region.html) which slightly changes the way it deploys.
* Added `--debug` flag: We also improved a little bit the implementation so that it's easier to debug a failed deployment.
* Added `--timeout` flag: Make the timeout configurable and increase it by default. Some deployments failed due to this too low timeout.
=> Add support for multi-regions

lib/dpl/provider/pages.rb
Should fix https://travis-ci.community/t/failed-to-deploy-because-of-ruby-error/1143 according to https://travis-ci.community/t/failed-to-deploy-because-of-ruby-error/1143/7
=> Clean up after a failed `git clone'

lib/dpl/provider/lambda.rb
https://travis-ci.community/t/aws-lambda-deployment-provider-equals-sign-in-environment-variables-value/4247
When the env var contains `=`, the right of it is dropped.
=> Preserve "=" in the RHS of env var

.travis/providers/aws-elasticbeanstalk/prepare, .travis/providers/aws-elasticbeanstalk/travis.yml, lib/dpl/providers/elasticbeanstalk.rb, spec/dpl/providers/elasticbeanstalk_spec.rb, spec/spec_helper.rb, spec/support.rb, spec/support/now.rb
This should address https://github.com/travis-ci/dpl/issues/411, and supersedes https://github.com/travis-ci/dpl/pull/885
It uses a Rubygem that ports Python's `PathSpec` (which is what the EB CLI uses) https://github.com/highb/pathspec-ruby.
FWIW the Python implementation in the EB CLI currently is:
```python
def get_ebignore_list():
location = get_ebignore_location()
if not os.path.isfile(location):
return None
with codecs.open(location, 'r', encoding='utf-8') as f:
spec = PathSpec.from_lines('gitwildmatch', f)
ignore_list = [f for f in spec.match_tree(get_project_root())]
ignore_list.append('.ebignore')
return ignore_list
```
=> honor .ebignore for excluding files from the zip

lib/dpl/providers/cloudformation.rb
Changes:
- Removed requirement for AWS credentials - it will try the default chain if not provided as parameters (allows to use global env variables and saves some repetitions in .travis.yml later on)
- Fixed events printing
- added/fixed template definition (changed method of `template` -> `template_param` because of infinite loop in messages)
- moved error messages from `errs` to `msgs` - `Cl?` doesn't handle `errs` section (yet?)
- Syntax errors fix for EVENT_KEYS
=> Fixes for cloudformation provider

lib/dpl/providers/bintray.rb
Fixed several issues with the original branch:
* When updating file metadata the request body should be json-encoded
* When updating file metadata the request should contain a `Content-Type` set to `application/json`
* When retrying there was no delay
* Failing retries was ignored silently
* There was a mistake that lead to upload only artifacts with the `listInDownloads` attribute but try to actually list all artifacts resulting in a `404` error for artifacts without `listInDownloads` 
Tested on https://github.com/loicalbertin/travis-dpl-bintray-test
See https://travis-ci.org/loicalbertin/travis-dpl-bintray-test/builds/573880501
=> Fix issues on sf_port_950 branch

.travis/providers/engineyard/prepare, lib/dpl/providers/bintray.rb, lib/dpl/providers/engineyard.rb, lib/dpl/providers/heroku.rb, lib/dpl/providers/npm.rb, lib/dpl/providers/surge.rb, lib/dpl/providers/testfairy.rb, spec/dpl/providers/engineyard_spec.rb
`engineyard-cloud-client` has a requirement on a really old `rest-client` version which now conflicts with the Gleis provider PR
=> Port engineyard provider to use the ey-core gem

lib/dpl/providers/lambda.rb, spec/dpl/providers/lambda_spec.rb
This ports the remaining runtime dependent separators and logic from https://github.com/travis-ci/dpl/pull/1018
The Java separator `::` was already ported in another PR (https://github.com/travis-ci/dpl/pull/1027).
=> lambda: more runtime dependent separators

lib/dpl/providers/s3.rb, spec/dpl/providers/s3_spec.rb
refers to https://github.com/travis-ci/dpl/issues/1079
can be tested with
```yaml
deploy:
provider: s3
force_path_style: true
edge:
branch: sf-s3-subdomain
```
=> add s3 --host_prefix

lib/dpl/providers/gae.rb, lib/dpl/providers/gcs.rb, spec/dpl/providers/gae_spec.rb, spec/dpl/providers/gcs_spec.rb
Using different versions of the SDK has started causing failures during dep install tests.
=> Google cloud sdk

README.md, lib/dpl/providers/npm.rb, spec/dpl/providers/npm_spec.rb
This PR introduces the `--dry-run` CLI parameter as described in the [npm CLI documentation](https://docs.npmjs.com/cli/publish.html#description).
The reason for this addition is, that there is currently no possibility of testing the `npm publish` option without actually uploading the package to the registry.
Due to the fact, that a version number cannot be re-used on npm once a package has been uploaded and released on the registry, it could cause issues in terms of the transparency between tagged versions vs. the actually released packages.
=> NPM: add --dry-run option

.travis/providers/snap/prepare, .travis/providers/snap/test, .travis/providers/snap/travis.yml, .travis/trigger, lib/dpl/providers/snap.rb, spec/dpl/providers/snap_spec.rb
Updates to fix and test snap deployment.
Before merging, this will require a handoff or collaborative access for:
(1) `dee-pee-ell-test` snap
(2) or `sed -i 's|dee-pee-ell-test|dpl-test|g'` to use `dpl-test` snap which I believe is owned by @svenfuchs.
SNAP_TOKEN may be generated using snapcraft with:
`snapcraft export-login --acls package_upload --snaps <snap-name> --channels edge -`
=> initial snap support

Rakefile
(the below command is what RubyMine runs on "reload rake tasks list")
```
C:\Users\Sasha\Documents\travis-dpl>"C:\Ruby24-x64\bin\ruby.exe"  "C:\Ruby24-x64\bin\bundle" exec C:\Ruby24-x64\bin\ruby
.exe C:\Ruby24-x64\bin\rake --tasks --trace
rake aborted!
NameError: uninitialized constant DPL
Did you mean?  Dpl
C:/Users/Sasha/Documents/travis-dpl/Rakefile:26:in `gem_version'
C:/Users/Sasha/Documents/travis-dpl/Rakefile:49:in `<top (required)>'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/applicat …
```
=> Fix "NameError: uninitialized constant DPL" on rake --tasks

lib/dpl/providers/elasticbeanstalk.rb
Currently, when deploying to Elastic Beanstalk with the `wait_until_deployed` flag set, `dpl` will only wait for up to 100 seconds before declaring the build has failed with a "Too many failures" error. However, this is not indicative of what the actual deploy status is. 
I raised this to @svenfuchs in https://github.com/travis-ci/dpl/issues/985. EB deploys generally take much more than 100 seconds when you choose rolling or immutable deploys. Mine take about 10 mins. In line with that, this PR:
- allows user to specify a time period to wait with a new `wait_until_deployed_timeout` flag
- use a default timeout of 600 seconds to allow for more complex deployments to succeed before terminating build
- prompt the user to use the new `wait_until_deployed_timeout` flag when the build …
=> Specify time to wait for deploy on AWS Elastic Beanstalk

lib/dpl/providers/convox.rb, spec/dpl/providers/convox_spec.rb
This PR solves issue with: 
- `$` sign in environment variables.
- adds new `env_names` method to allow defining variables names to be passed from the build (apart of using `VAR_NAME_FOO=${VAR_NAME_FOO}` which with longer names make a lot of deduplications.
=> Convox names

lib/dpl/providers/convox.rb, spec/dpl/providers/convox_spec.rb
In case of convox apps we found that it's good to have before/after deployment methods that are run with context of provider. Thanks to that user can have access to `convox` binary so just before deployment some `admin processes` can be run (https://12factor.net/admin-processes).
For post deployment tasks `run` can be used.
=> Convox prepare option

CHANGELOG.md, lib/dpl/providers/pages/api.rb, lib/dpl/providers/pages/git.rb, lib/dpl/providers/releases.rb
The octokit 4.14.0 gem is broken due to the new faraday release.
See: [https://github.com/octokit/octokit.rb/issues/1177](https://github.com/octokit/octokit.rb/issues/1177)
This patch updates the octokit version used by dpl to 4.15.0.
=> Fix #1146: update octokit version

README.md, bin/readme, lib/dpl/helper/interpolate.rb, lib/dpl/provider.rb, lib/dpl/provider/dsl.rb, lib/dpl/providers/codedeploy.rb, lib/dpl/providers/lambda.rb, lib/dpl/providers/pages/git.rb, spec/dpl/helper/interpolate_spec.rb
Allow safelisting interpolation vars on providers that expose interpolated strings, such as `commit_message` on `pages:git`, and add these to the generated documentation.
=> allow safelisting interpolation vars

lib/dpl/providers/gleis.rb
This PR updates the gleis gem dependency from version 0.6 to 0.7 for the Gleis provider as version 0.7.0 has been released yesterday (https://rubygems.org/gems/gleis).
=> update gleis gem dependency to 0.7.0

lib/dpl/providers/codedeploy.rb, spec/dpl/providers/codedeploy_spec.rb
Specifically, if the eventually returned status is not 'Succeeded', then
the deploy fails with a message indicating that waiting was terminated
and the returned status.
This change includes a test that asserts that the failure is correctly
raised in this case.
With some additional effort I could set up a script that should provoke
a non-'Succeeded' status code and prove out the integration itself,
please let me know if that's desired.
I'm definitely also open to feedback on the style of the returned
error message.
Closes: #1186
=> Fail CodeDeploy when wait_until_deployed fails

lib/dpl/providers/cloudfoundry.rb, spec/dpl/providers/cloudfoundry_spec.rb
Official instructions:
https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v7.md#installers-and-compressed-binaries
Also adding support to the new CLI v7 has a new strategy option for rolling deploy:
https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html
Fix #910
=> Update CloudFoundry CLI to v7

lib/dpl/assets/dpl/git_ssh, lib/dpl/providers/pages/git.rb, spec/dpl/providers/pages/git_spec.rb
Remove a hardcoded github.com in the pages provider's deploy key validation check, which breaks deployment pipelines running against GitHub Enterprise.
This fixes usage of read-write deploy keys with the pages deploy_key option when the Travis default private key is only authorized for read-only access.
This makes debugging broken deployments slightly easier, as error messages are no longer suppressed.
---
Signed-off-by: afzhou <afzhou@ibm.com>
=> pages: Fix deploy keys

.travis.yml, dpl.gemspec, lib/dpl/ctx/bash.rb, lib/dpl/providers/cloudformation.rb, lib/dpl/providers/codedeploy.rb, lib/dpl/providers/ecr.rb, lib/dpl/providers/elasticbeanstalk.rb, lib/dpl/providers/heroku.rb, lib/dpl/providers/lambda.rb, lib/dpl/providers/netlify.rb, lib/dpl/providers/opsworks.rb, lib/dpl/providers/puppetforge.rb, lib/dpl/providers/s3.rb, lib/dpl/providers/transifex.rb, lib/dpl/version.rb, spec/dpl/ctx/bash_spec.rb
ticket [TBT-4](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=4) PRs: #1276 #1282
=> Release 2024 06 17 TBT-4
