- lib/dpl/provider/chef_supermarket.rb
Fixes issue introduced after #201
> Fix chef compatibility with ruby 1.9

- lib/dpl/provider/heroku/api.rb
- spec/provider/heroku_api_spec.rb
fixes #209
happy to get feedback as my ruby is rusty and I chose to follow the existing style in this file.  FYI I've tested this manually against a failing build and a successful build.
> respect build exit code in heroku api provider

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/elastic_beanstalk.rb
This should resolve travis-ci/dpl#218.  Also there is a fix to make the region option actually optional as is stated in the documentation.  Thanks to @zabawaba99 for the help.
> Fix for issue #218

- README.md
- lib/dpl/provider/elastic_beanstalk.rb
- spec/provider/elastic_beanstalk_spec.rb
This is an attempt to resolve #172.
I'd like to add some tests for this but I'm not too sure how to go about testing it. Any suggestions?
> Specifying s3 folder location for beanstalk deploy

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/bintray.rb
- spec/provider/bintray_spec.rb
This pull request is following https://github.com/travis-ci/dpl/pull/256
It includes all comments provided by @rtyler and @BanzaiMan
Please let me know if anything else is needed to add the new Bintray provider and thanks a lot for helping with this!
> Bintray provider

- lib/dpl/provider/heroku/api.rb
- spec/provider/heroku_api_spec.rb
See https://devcenter.heroku.com/articles/build-and-release-using-the-api#beta-streaming-build-output
> [NON-TESTED] change away from edge api

- .coveralls.yml
- README.md
- dpl.gemspec
- spec/spec_helper.rb
This resolves https://github.com/travis-ci/dpl/issues/59. 
@rkh: You'll need to set up dpl on http://coveralls.io.
> Added Coveralls.io integration

- lib/dpl/provider.rb
- lib/dpl/provider/transifex.rb
- spec/provider/transifex_spec.rb
/cc @emdantrim @diegobz
Example usage in `.travis.yml`:
```
deploy:
provider:
transifex:
username: someuser
password:
secure: ABCD1234...5678WXYZ
```
> Transifex provider implementation

- README.md
Adding docs for Atlas. It appears that the dpl gem hasn't been updated with the latest Atlas provider, so I wasn't able to test, but I think this should get us close.
> Atlas Docs

- lib/dpl/provider/pypi.rb
- spec/provider/pypi_spec.rb
Fix for https://github.com/travis-ci/dpl/issues/253
> Use twine for PyPI uploads.

- lib/dpl/provider/heroku/api.rb
This feature is now pulled into our main API version. (It was when #241 got merged too.)
> Use main version

- lib/dpl/provider/chef_supermarket.rb
> Fix chef supermarket endpoint url

- lib/dpl/provider.rb
- lib/dpl/provider/deis.rb
- spec/provider/deis_spec.rb
Reverts travis-ci/dpl#297
The merge introduced build failure https://travis-ci.org/travis-ci/dpl/builds/75989969 which I cannot yet explain. I'm reverting this to see if it fixes the build.
> Revert "Improved and updated the Deis provider"

- lib/dpl/provider/npm.rb
- spec/provider/npm.rb
> add some logic to clean up npmrc file after publish

- lib/dpl/provider/deis.rb
- spec/provider/deis_spec.rb
> revert to cli_version as the name change breaks everyone's builds

- Gemfile
- lib/dpl/provider/lambda.rb
- spec/provider/lambda_spec.rb
Quick fix as described here: https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md#2038-2015-04-09
> Use LambdaPreview and unlock aws-sdk

- lib/dpl/provider/gae.rb
This is [fixed with version 0.9.79](https://code.google.com/p/google-cloud-sdk/issues/detail?id=228#c4) which was [released recently](https://groups.google.com/forum/#!topic/google-cloud-sdk-announce/vTSmrKMK4cY).
> gae: Remove workaround for gcloud issue

- README.md
- lib/dpl/provider/gae.rb
- spec/provider/gae_spec.rb
> gae: Adapt to gcloud-0.9.82

- lib/dpl/provider/bintray.rb
As see in build: https://travis-ci.org/yahoo/elide/builds/86486285
> Fix undefined local variable errors on deploy

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/scalingo.rb
- spec/provider/scalingo_spec.rb
Add of [Scalingo](https://github.com/Scalingo/) provider to dpl.
> Scalingo provider

- lib/dpl/provider/azure_webapps.rb
> Azure Deployment: skip_cleanup

- lib/dpl/provider/gae.rb
The right component to be installed is "app" and not "preview", the "preview" component has disappeared.
This should fix #350
> Changed the additional components to be installed

- README.md
Fixing a minor typo in the README file.
> Correcting typo.

- lib/dpl/provider/gae.rb
Fixes https://github.com/travis-ci/dpl/issues/383.
> Add space to separate the args

- lib/dpl/provider/anynines.rb
- spec/provider/anynines_spec.rb
Now cf api endpoint is set correctly, furthermore user can login and set organization and spaces.
> Fixed provider anynines to work in TravisCI

- README.md
- lib/dpl/provider/pypi.rb
- spec/provider/pypi_spec.rb
This would allow setting the PyPI config variables conditionally in a pre step for example.
> Added ability to specifc PyPI config options as environment variables.

- lib/dpl/provider.rb
Resolves https://github.com/travis-ci/travis-ci/issues/5518
> Log `git stash` command

- lib/dpl/provider/bintray.rb
> Read files in binary mode for bintray provider

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/surge.rb
- spec/provider/surge_spec.rb
Test run: https://travis-ci.org/mathiasrw/travis-loves-surge/builds/123186780
Works even if the user `cd`s at any step.
> Let Travis deploy to Surge.sh

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/catalyze.rb
- spec/provider/catalyze_spec.rb
I created a dpl provider for [Catalyze](https://catalyze.io/). I can't give you a link to an example build since since it is a private repository but I have tested it and it works.
> Created a provider for Catalyze

- lib/dpl/provider/appfog.rb
- lib/dpl/provider/packagecloud.rb
- lib/dpl/provider/puppet_forge.rb
for puppet_forge, appfog and packagecloud
> Pin json_pure to '< 2.0'

- Gemfile
- lib/dpl/provider/cloud_files.rb
Fixes https://github.com/travis-ci/dpl/issues/506.
> Require less on CloudFiles

- lib/dpl/provider/firebase.rb
- spec/provider/firebase_spec.rb
> Update to firebase-tools v3

- README.md
- lib/dpl/provider.rb
- lib/dpl/provider/pages.rb
Implements #34. Improvements are welcome :)
Successful build with this provider: https://travis-ci.org/webknjaz/dpl-gh-pages/builds/156862649
Multiple providers: https://travis-ci.org/webknjaz/dpl-gh-pages/builds/161555677
> Add Github Pages provider

- lib/dpl/provider/gae.rb
- spec/provider/gae_spec.rb
> removed the preview flag from the gae provider

- Gemfile
> Revert "Pin nokogiri at ~>1.6.8 that uses ruby >=1.9.2"

- lib/dpl/provider/cloud_files.rb
Resolves https://github.com/travis-ci/dpl/issues/561
> Pin nokogiri to '~> 1.6.8.1' for cloud_files

- README.md
Add prerelease as option for GitHub releases to README.md
> [README.md] Add prerelease as option for GitHub releases

- lib/dpl/provider/testfairy.rb
- spec/provider/testfairy_spec.rb
Code fix and test for https://github.com/travis-ci/dpl/issues/579
> Fix handling of boolean parameters check in testfairy provider

- README.md
- lib/dpl/provider/bluemix_cloud_foundry.rb
Signed-off-by: Adam King <rak@us.ibm.com>
> Add the Bluemix CloudFoundry Germany region.

- lib/dpl/provider/elastic_beanstalk.rb
- spec/provider/elastic_beanstalk_spec.rb
> elasticbeanstalk zip_file to uses File.expand_path

- lib/dpl/provider/cloud_foundry.rb
- spec/provider/cloudfoundry_spec.rb
> raises error when cf push failed

- lib/dpl/provider/heroku/generic.rb
- spec/provider/heroku_spec.rb
> Remove Heroku email address from logs

- lib/dpl/provider/pages.rb
When `gh_url` option is set, respect it to set the git endpoint.
> Fix Pages provider for Enterprise

- README.md
- lib/dpl/provider/testfairy.rb
- spec/provider/testfairy_spec.rb
* remove UPLOAD_SIGNED
* update README file
* update stestfairy_spec.rb
> Testfairy remove instrumentation

- dpl-puppet_forge.gemspec
Resolves https://github.com/travis-ci/dpl/issues/772
> Add json_pure to puppet_forge runtime dependency

- lib/dpl/provider/pages.rb
Resolves https://github.com/travis-ci/travis-ci/issues/9312.
> Access gh_token & gh_remote_url correctly

- lib/dpl/provider/bintray.rb
Resolves https://github.com/travis-ci/travis-ci/issues/9314
> Fix bintray authentication

- lib/dpl/provider/lambda.rb
- spec/provider/lambda_spec.rb
> Fix dot_match option

- README.md
Fixing a minor typo that was causing a broken link in the Lambda section.
> Fixing minor typo

- lib/dpl/provider/cloud_foundry.rb
- spec/provider/cloud_foundry_spec.rb
> Service Account Authentication for Cloud Foundery Provider

- lib/dpl/provider/s3.rb
> Revert "Provide `quiet` option to S3 provider"

- README.md
Document the new snap provider.
> Add snap docs to the README

- lib/dpl/provider/heroku/api.rb
- spec/provider/heroku_spec.rb
This supersedes https://github.com/travis-ci/dpl/pull/714.
> Pass `-sS` to `curl` invoked from Heroku deployment

- lib/dpl/provider/anynines.rb
- lib/dpl/provider/bluemix_cloud_foundry.rb
- lib/dpl/provider/cloud_foundry.rb
- spec/provider/anynines_spec.rb
- spec/provider/bluemix_cloud_foundry_spec.rb
- spec/provider/cloud_foundry_spec.rb
Fixes https://github.com/travis-ci/dpl/issues/915.
> Test OS from `uname` output

- lib/dpl/provider/releases.rb
The commit may not exist on the repo specified.
Resolves #928.
> Set target_commitish only for same repo

- lib/dpl/provider/firebase.rb
Release notes can be found [here](https://github.com/firebase/firebase-tools/releases)
> Upgrade Firebase to v6.1

- lib/dpl/provider/s3.rb
Fixed attempt to compare string with integer, which previously failed.
> Fixed configurable "max_thread" issue within S3 provider

- lib/dpl/provider/elastic_beanstalk.rb
> Ignore occasional (and seemingly harmless) ServiceError from ElasticBeanstalk

- .travis.yml
To conform to the correct schema.
> Tweak "Deploy" stage configurations

- lib/dpl/helper/config_file.rb
- lib/dpl/helper/env.rb
- lib/dpl/provider.rb
- lib/dpl/providers/codedeploy.rb
- lib/dpl/providers/elasticbeanstalk.rb
- lib/dpl/providers/lambda.rb
- lib/dpl/providers/opsworks.rb
- lib/dpl/providers/s3.rb
- spec/dpl/providers/codedeploy_spec.rb
- spec/dpl/providers/elasticbeanstalk_spec.rb
- spec/dpl/providers/lambda_spec.rb
- spec/dpl/providers/opsworks_spec.rb
- spec/dpl/providers/s3_spec.rb
- spec/support/cl.rb
> allow using config files on AWS providers (ports #875)

- lib/dpl/providers/pypi.rb
- spec/dpl/providers/pypi_spec.rb
```yaml
deploy:
provider: pypi
edge:
branch: sf-pypi-upload-docs
⋮
```
> remove skip_ from upload_docs (see #835)

- lib/dpl/providers/s3.rb
- spec/dpl/providers/s3_spec.rb
```yaml
deploy:
provider: s3
edge:
branch: sf-s3-file-specific-opts
⋮
```
> fix file specific cache control and expires opts (ports #958)

- lib/dpl/providers/s3.rb
- spec/dpl/providers/s3_spec.rb
```yaml
deploy:
provider: s3
edge:
branch: sf-s3-verbose
⋮
```
> add s3 --verbose (ports #882)

- lib/dpl/providers/lambda.rb
- spec/dpl/providers/lambda_spec.rb
```yaml
deploy:
provider: lambda
edge:
branch: sf-lambda-layers
⋮
```
> add lambda --layers (see #933)

- lib/dpl/providers/releases.rb
and suggest possible remedy.
See https://travis-ci.community/t/github-returns-404-when-trying-to-deploy-using-github-releases/4770/5?u=banzaiman
> Trap Octokit::NotFound exception

- lib/dpl/providers/pypi.rb
- spec/dpl/providers/pypi_spec.rb
```yaml
deploy:
provider: pypi
edge:
branch: sf-twine-check
⋮
```
> add pypi twine check (see #994)

- lib/dpl/providers/gae.rb
- spec/dpl/providers/gae_spec.rb
```yaml
deploy:
provider: gae
edge:
branch: sf-gae-configs
⋮
```
> gae allow multiple configs (see #829)

- lib/dpl/providers/codedeploy.rb
- lib/dpl/providers/elasticbeanstalk.rb
- lib/dpl/providers/lambda.rb
- lib/dpl/providers/opsworks.rb
- lib/dpl/providers/s3.rb
- spec/dpl/providers/codedeploy_spec.rb
- spec/dpl/providers/elasticbeanstalk_spec.rb
- spec/dpl/providers/lambda_spec.rb
- spec/dpl/providers/opsworks_spec.rb
- spec/dpl/providers/s3_spec.rb
- spec/spec_helper.rb
- spec/support.rb
- spec/support/helpers.rb
- spec/support/matchers.rb
- spec/support/matchers/aws.rb
```yaml
deploy:
provider: [provider]
edge:
branch: sf-aws-sdk-v3
⋮
```
> port AWS providers to sdk v3 (ports #863)

- lib/dpl/providers/chef_supermarket.rb
- spec/dpl/providers/chef_supermarket_spec.rb
```yaml
deploy:
provider: chef-supermarket
edge:
branch: sf-cookbook-name
⋮
```
> read cookbook name from metadata (ports #968)

- lib/dpl/providers/releases.rb
- spec/dpl/providers/releases_spec.rb
```yaml
deploy:
provider: pages
edge:
branch: sf-releases-release-notes
⋮
```
> rename --body to --release_notes, add --release_notes_file (see #155)

- lib/dpl/assets/git/detect_private_key
- lib/dpl/ctx/bash.rb
- lib/dpl/ctx/test.rb
- lib/dpl/provider.rb
- lib/dpl/providers/pages/git.rb
- spec/dpl/providers/pages/git_spec.rb
re https://github.com/travis-ci/dpl/issues/1084
> change --deploy_key to accept a path

- lib/dpl/providers/npm.rb
- spec/dpl/providers/npm_spec.rb
see https://github.com/travis-ci/dpl/issues/1118
allows one or many scripts to be run using `npm run [script]`. e.g.
```yaml
deploy:
- provider: npm
edge: 
branch: sf-run_script
run_script: publish
```
or
```yaml
deploy:
- provider: npm
edge: 
branch: sf-run_script
run_script: 
- one
- other
```
> add npm --run_script

- CONTRIBUTING.md
> CONTRIBUTING: fix link for test_install

- lib/dpl/providers/cloudformation.rb
Changeset name has constraints: 
```Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]* ```
> Fixed changeset name format.

- lib/dpl/providers/flynn.rb
> Add Provider Flynn

- README.md
- bin/readme
- lib/dpl/providers/elasticbeanstalk.rb
- spec/dpl/providers/elasticbeanstalk_spec.rb
This fixes a condition in https://github.com/travis-ci/dpl/pull/1172
> Elastic Beanstalk provider improvements

- lib/dpl/providers/lambda.rb
Add Nodejs16 and Nodejs14 runtimes
> Update NodeJS Lambda runtime

- lib/dpl/providers/pages/git.rb
- spec/dpl/providers/pages/git_spec.rb
removed broken ssh_key display
removed git debug
to be re-added under a 'verbose' flag + ssh fix
> partial revert for ghpages

- lib/dpl/version.rb
> Bug fix cycle 10

- Gemfile
- dpl.gemspec
- lib/dpl/providers/chef_supermarket.rb
- lib/dpl/providers/pages/api.rb
- lib/dpl/version.rb
> 2.0.5.2.beta.1
